config/routes.rb
Rails.application.routes.draw do
 
  resources :pollies

  resources :vsers

  resources :maps
  resources :places

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Blazer::Engine, at: "blazer"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


post '/quote', to: 'quotes#create'
post '/lead', to: 'leads#create'
post '/intervention', to: 'intervention#create'

  
  root 'pages#index'



 get '/intervention', to: 'pages#intervention'

  get '/commercial', to: 'pages#commercial'

  
  get '/residential', to: 'pages#residential'
  resources :leads
  # resources :quotes
  get '/index', to: 'pages#index'
  get '/quotes', to: 'pages#quotes'

  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'

get '/map', to: 'admin#map'

resources :maps

# courses = books  |  course = book  |  location = author
# get 'get_books_by_author/:author_id', to: 'books#get_books_by_author' 
get 'get_building_by_customer/:customer_id', to: 'intervention#get_building_by_customer'
get 'get_battery_by_building/:building_id', to: 'intervention#get_battery_by_building'
get 'get_column_by_battery/:battery_id', to: 'intervention#get_column_by_battery'   
get 'get_elevator_by_column/:column_id', to: 'intervention#get_elevator_by_column'

get '/intervention', to: 'page#intervention'



end

app/models/address.rb
class Address < ApplicationRecord
  # attr_accessor :number_and_street, :city, :postal_code, :country    s

  geocoded_by :kaddress
  def kaddress
    [number_and_street, city, postal_code, country].compact.join(', ')
  end
  def customerInfo
    [customer.CompanyName, customer.FullNameServiceTechAuth]
  end
  after_validation :geocode

    has_one :building
    has_one :customer
    
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/battery.rb
class Battery < ApplicationRecord

    belongs_to :employee
    belongs_to :building
    has_many :columns
    belongs_to :intervention
end

app/models/building.rb
class Building < ApplicationRecord

    belongs_to :address
    belongs_to :customer
    has_many :batteries
    has_one :building_detail
    belongs_to :intervention 

end

app/models/column.rb
class Column < ApplicationRecord

    belongs_to :battery
    has_many :elevators
    belongs_to :intervention

end

app/models/customer.rb
class Customer < ApplicationRecord
    include ActiveModel::Dirty

    belongs_to :user
    has_many :buildings
    belongs_to :address
    belongs_to :intervention

end

app/models/dim_customer.rb
class DimCustomer < SecondBase::Base
end

app/models/elevator.rb
require 'rubygems'
require 'twilio-ruby'
class Elevator < ApplicationRecord
  include ActiveModel::Dirty

  belongs_to :column
  has_many :intervention

  require 'slack-notifier'

  oldstatus = ''
  before_update do
    oldstatus = self.Status_was
  end

  after_update do


    if oldstatus != self.Status



      notifier = Slack::Notifier.new ENV["slackwebhook"]
      notifier.ping "The Elevator #{id} with Serial Number #{self.SerialNumber} changed status from #{oldstatus} to #{self.Status}"
    end
  end

 
  
 after_update do
  if self.Status = "Intervention"
    
    @client = Twilio::REST::Client.new(Figaro.env.account_sid, Figaro.env.auth_token)

    message = @client.messages.create(
     body: 'This is the notification that one elevator is under intervention status!',
     from: '+19804009897',
     to: '+17278559151'
    )

    puts message.sid
end
    

end
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :battery
    belongs_to :user
end

app/models/fact_contact.rb
class FactContact < SecondBase::Base
end

app/models/fact_quote.rb
class FactQuote < SecondBase::Base
end

app/models/intervention.rb
class Intervention < ApplicationRecord

    belongs_to :customer
    belongs_to :building
    belongs_to :battery
    belongs_to :column
    belongs_to :elevator
end

app/models/lead.rb
class Lead < ApplicationRecord

  # after_create :sendAttachedFile
  # require 'dropbox_api'

  # has_one_attached :image
  # validate :acceptable_image
  #
  # def acceptable_image
  #   return unless image.attached?
  #
  #   if image.byte_size > 1.megabyte
  #     image_size = (image.byte_size / 1_000_000.0).round(2)
  #     errors.add(:image, "size #{image_size} MB exceeds 1 MB limit")
  #   end
  #
  #   acceptable_types = ['image/jpeg', 'image/jpg', 'image/png']
  #   errors.add(:image, 'must be a JPEG or PNG') unless acceptable_types.include?(image.content_type)
  # end
  #
  #
  # # define the after_save action to remove an image
  # def remove_attached_image?
  #   remove_attached_image == '1'
  # end
  #
  # def purge_attached_image
  #   image.purge_later
  # end
  #
  # attr_accessor :remove_attached_image
  # after_save :purge_attached_image, if: :remove_attached_image?
  # def sendAttachedFile
  #   unless self.Attached_file.nil?
  #     # varNameForPath = '/client_folder'
  #     client = DropboxApi::Client.new(ENV["OAuthToken"])
  #     begin
  #       #   #   #   client.upload("/#{self.Full_name_of_the_contact}/file", self.Attached_file)
  #       #   #
  #       #   #   begin
  #       client.create_folder("/DoomSlayer")
  #       file_content = IO.read(self.Attached_file)
  #       #   #
  #       #   #   # test = Lead.first
  #       #   #   # binary = test.Attached_file
  #       #   #   #
  #       #   #   # client = Dropbox...new...
  #       #   #   #   client.upload(somePath, binary)
  #       #   #
  #       # client.upload("/DoomSlayer/duck", self.Attached_file)
  #       client.upload("/DoomSlayer/duck", file_content)
  #     end
  #   end
  # end

    # require 'sendgrid-ruby'
    # include SendGrid
    # #actually sends email after lead is created
    # after_create :send_email1
    # def send_email1
    #     send_email(self)
    # end
    # def send_email(lead)
    #     mail = Mail.new
    #     personalization0 = Personalization.new
    #     personalization0.add_to(Email.new(email: "#{lead.email}"))
    #     mail.add_personalization(personalization0)
    #     mail.from = Email.new(email: 'baseballperks318@gmail.com') #<---------- register an email with sendgrid and ad it here
    #     mail.reply_to = Email.new(email: "#{lead.email}")
    #     mail.subject = 'Thankyou for your submission'
    #     email_content = "<p> Greetings #{lead.Full_name_of_the_contact}.</p>
    #     <p>We thank you for contacting Rocket Elevators to discuss the opportunity
    #     to contribute to your project #{lead.Project_name}. A representative from our
    #     team will be in touch with you very soon. We look forward to demonstrating
    #     the value of our solutions and helping you choose the appropriate product
    #     given your requirements. </p>
    #     <p>We'll Talk soon, </p>
    #     <p>The Rocket Team </p>"
    #     mail.add_content(Content.new(type: 'text/html', value: email_content))
    #     sg = SendGrid::API.new(api_key: ENV['sendgridAPI'])
    #     response = sg.client.mail._('send').post(request_body: mail.to_json)
    #     puts "#############################################################"
    #     puts response.status_code
    #     puts response.body
    #     puts response.headers
    # end

end

app/models/map.rb
class Map < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/polly.rb
class Polly < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :employee
    has_many :customer

end

app/models/vser.rb
class Vser < ApplicationRecord
end

app/controllers/maps_controller.rb
class MapsController < InheritedResources::Base

  private

    def map_params
      params.require(:map).permit()
    end

end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/map/_map.html.erb
<%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Figaro.env.google_maps_api_key%>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap()
    });
  </script>
<% end %>
<div class="map-container">
<div 
    id="breweries" style="display:none">
    <ol>
      <% Address.all.each do |address| %>
      <% b = address.building%>      
         <% no_of_column = 0 %>
         <% no_of_elevator = 0 %>
         <% for c in b.battery_ids do %>
            <% no_of_column += Column.where(battery_id: c).count%>
            <% columns = Column.where(battery_id:c)%>
            <% for e in columns do %>
              <% no_of_elevator += Elevator.where(Column_id: e).count %>
              <% end %>
          <%end %>
          <% no_of_floor = Quote.find(address.id).number_of_floors%>
          <li
          class="address-list-item"
          data-latitude=<%= address.latitude %>
          data-longitude=<%= address.longitude %>
          data-location1=<%= address.number_and_street%>
          data-location2=<%= address.city%>
          data-location3=<%= address.postal_code%>
          data-location4=<%= address.country%>
          data-client=<%= address.customerInfo[0]%>
          data-tec=<%= address.customerInfo[1]%>
          data-batteries=<%=b.battery_ids.count%>
          data-columns=<%=no_of_column%>
          data-elevators=<%=no_of_elevator%>
          data-buildingfloors=<%=no_of_floor%>

        >
        </li>
        <% end %>
     
    </ol>
</div>
<%# <div id="map" ></div> %>
<div id="map" class="z-depth-1-half map-container" style="width: 100vw">
  <iframe  frameborder="0" src='https://maps.googleapis.com/maps/api/js?key='+Figaro.env.google_maps_api_key,defer: true
    style="border:0" allowfullscreen></iframe>
</div>

</div>

<%= javascript_tag 'map' %>
<%# <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Figaro.env.google_maps_api_key,defer: true%> %>
<script>
function initMap() {
  var lat=35.1774;
  var lng=-97.4118;

  var myCoords = new google.maps.LatLng(lat, lng);
  var mapOptions = {
      center: myCoords,
      zoom: 4,
      mapTypeId: google.maps.MapTypeId.ROADMAP

  };
  var map = new google.maps.Map(document.getElementById('map'), mapOptions);
  let locations = [];
  document.querySelectorAll("li.address-list-item").forEach(address => {
          let position = [
              
              address.getAttribute("data-latitude"),
              address.getAttribute("data-longitude"),
              address.getAttribute("data-location1"),
              address.getAttribute("data-location2"),
              address.getAttribute("data-location3"),
              address.getAttribute("data-location4"),
              // address.getAttribute("data-location5"),
              address.getAttribute("data-client"),
              address.getAttribute("data-tec"),
              address.getAttribute("data-batteries"),
              address.getAttribute("data-columns"),
              address.getAttribute("data-elevators"),
              address.getAttribute("data-buildingfloors")
              
          ]
          locations.push(position)
  });
  

  var infowindow =  new google.maps.InfoWindow({});
  var marker, count;
  for (count = 0; count < locations.length; count++) {
      marker = new google.maps.Marker({
          position: new google.maps.LatLng(locations[count][0], locations[count][1]),
          map: map,
          title: locations[count][2] + locations[count][3]+ locations[count][4]+locations[count][5],
      
      });
  google.maps.event.addListener(marker, 'click', (function (marker, count) {
        return function () {
           infowindow.setContent("<p>" +"Building Location: " +locations[count][2]+", "+
             locations[count][3]+", "+ locations[count][4]+", "+locations[count][5]+
             "<br /> Company Name: "+locations[count][6]+
             "<br /> Full name of the tech: "+locations[count][7]+
             "<br /> No.of Batteries: " +locations[count][8] +
              "<br /> No.of Columns: " + locations[count][9]+
               "<br /> No.of Elevators: " + locations[count][10] +
                "<br /> No.of Floors: " + locations[count][11]+"</p>");
            infowindow.open(map, marker);
          
        }
      })(marker, count));
    }

}
</script>

app/views/maps/index.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap()
    });
  </script>
<% end %>
<div class="map-container">
<div 
    id="breweries" style="display:none">
    <ol>
      <% Address.all.each do |address| %>
      <% b = address.building%>      
         <% no_of_column = 0 %>
         <% no_of_elevator = 0 %>
         <% for c in b.battery_ids do %>
            <% no_of_column += Column.where(battery_id: c).count%>
            <% columns = Column.where(battery_id:c)%>
            <% for e in columns do %>
              <% no_of_elevator += Elevator.where(Column_id: e).count %>
              <% end %>
          <%end %>
          <% no_of_floor = Quote.find(address.id).number_of_floors%>
          <li
          class="address-list-item"
          data-latitude=<%= address.latitude %>
          data-longitude=<%= address.longitude %>
          data-location1=<%= address.number_and_street%>
          data-location2=<%= address.city%>
          data-location3=<%= address.postal_code%>
          data-location4=<%= address.country%>
          data-client=<%= address.customerInfo[0]%>
          data-tec=<%= address.customerInfo[1]%>
          data-batteries=<%=b.battery_ids.count%>
          data-columns=<%=no_of_column%>
          data-elevators=<%=no_of_elevator%>
          data-buildingfloors=<%=no_of_floor%>

        >
        </li>
        <% end %>
     
    </ol>
</div>
<%# <div id="map" ></div> %>
<div id="map" class="z-depth-1-half map-container" style="width: 100vw">
  <iframe  frameborder="0" src='https://maps.googleapis.com/maps/api/js?key='+Figaro.env.google_maps_api_key,defer: true
    style="border:0" allowfullscreen></iframe>
</div>

</div>

<%= javascript_tag 'map' %>
<%# <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Figaro.env.google_maps_api_key,defer: true%> %>